### ISSUE TITLE
About the mesh reconstruction

### ISSUE THREAD

**Issue by 00Haocheng** [Tiena-Li/learn-gs-slam#1]
Thank you very much for sharing such an excellent project！ I would like to ask if this code can obtain a mesh file with color.

**Comment by Tiena-Li** [comment]
I'm sorry for replying you so late, I just noticed this message. qwq
First of all, I am not the author of the original MonoGS repository. I just added some Chinese comments when I read the code myself.
The original repository address is: https://github.com/muskie82/MonoGS Maybe you can get more information by asking here.
And I am a beginner, my ability is limited. I think this code does not have the part of getting colored mesh from Gaussian, but it is feasible to get point cloud from Gaussian.
As far as I know, there are SuGar and 2dgs that can extract mesh, but both of them are offline.
SuGar: https://github.com/Anttwo/SuGaR
2dgs: https://github.com/hbb1/2d-gaussian-splatting

**Comment by 00Haocheng** [comment]
Thank you for your reply. It seems that MonGS does not provide any code about mesh generation. However, your comments still helped me a lot in understanding the code. I have also been reading related content about 2dgs recently.  Thank you very much， I wish us all the best！
